### ISSUE TITLE
Can users add custom image/logo

### ISSUE THREAD

**Issue by Arakistech** [notrab/headless-dropshipping-starter#102]
Hi,

I would like users to be able to upload and use their own image/logo. What would be required for that?

regards

**Comment by notrab** [comment]
Hi @Arakistech 

Can you explain what you mean by users uploading their own image/logo? Do you mean to Printful or for the starter itself? Printful has an API you can use to get previews and then use that for the print but it's a bit outside the scope of this project (for now).

**Comment by camel113** [comment]
That would be very interesting. I am currently struggling to add let users add their custom text on products.

**Comment by lowfidelityart** [comment]
Bump.

Which .js file requires changes to customise your default branding 'Headless Dropshipping Starter'?

**Comment by notrab** [comment]
That is here: https://github.com/notrab/headless-dropshipping-starter/blob/main/src/components/Layout.tsx#L48

**Comment by lowfidelityart** [comment]
Much appreciated
