### ISSUE TITLE
Consider adding product detail pages

### ISSUE THREAD

**Issue by fuzenco** [notrab/headless-dropshipping-starter#13]
Really love this. I’d like to see the ability to click a product and see a detail view/page. Other than that, this is perfect.

**Comment by notrab** [comment]
A great suggestion!

I decided to leave this out for the sake of the starter to keep it simple without bringing in another service, such as a CMS API.

**Comment by danielroot** [comment]
Would love this feature too! Having ability to show larger product images and have a dedicated URL for each product would be awesome :) Thanks so much for this really cool starter kit!

**Comment by UnionOfAppeals** [comment]
> A great suggestion!
> 
> I decided to leave this out for the sake of the starter to keep it simple without bringing in another service, such as a CMS API.
> 
> Happy to consider "addons" for those who want this though 😄

How can we get this "addon"?

**Comment by notrab** [comment]
@UnionOfAppeals I'd need to build it, or approve a Pull Request if someone else wants to tackle it 😄

**Comment by notrab** [comment]
I'm working on product pages right now in another branch 🚀
