### ISSUE TITLE
when i click the icon，it doesn't show the register dialog box

### ISSUE THREAD

**Issue by zhuyanxuan** [notrab/headless-dropshipping-starter#24]
![image](https://user-images.githubusercontent.com/12567289/123774195-c519e200-d8ff-11eb-951b-8d80e99f273c.png)

**Comment by notrab** [comment]
@zhuyanxuan on the hosted demo, or your own install? Working fine on the hosted demo for me.

What happens if you go to `/#/signin`?

I'll need some more info to help debug this.

**Comment by zhuyanxuan** [comment]
I run it locally. I've seen your video. I need to realize this function myself, right?
