### ISSUE TITLE
Variants not pulling through sizes

### ISSUE THREAD

**Issue by christopherdowson** [notrab/headless-dropshipping-starter#42]
I've just checked with a fresh install (just to check it wasn't something I'd accidentally changed as I'm still learning React) and it seems that the variant information isn't being pulled through from Printful at all. Just the colour.

![image](https://user-images.githubusercontent.com/6522912/143912976-b6f71814-13a2-47a9-a68f-c8bbb6cdbd45.png)

Have they updated their API? The issue was intermittent at first, but now it seems to be everything.

**Comment by notrab** [comment]
Hey @christopherdowson 

I just checked this with my own store, and it seems fine.

It may have something to do with the names of the product in Printful. Can you screenshot your product inventory?

Do the names look similar to this, or are they formatted different?

<img width="1145" alt="CleanShot 2021-11-29 at 17 29 54@2x" src="https://user-images.githubusercontent.com/950181/143915123-ccb789fc-da47-46df-bb33-a23b1e9e0624.png">

The code for the variant picker values is made up of this function: https://github.com/notrab/headless-dropshipping-starter/blob/main/src/lib/format-variant-name.ts

**Comment by christopherdowson** [comment]
You know, it's just that obvious.😂

I'll double check but I think you've got it.

Thank you.

**Comment by notrab** [comment]
Awesome! Let me know, feel free to [schedule some time](https://savvycal.com/notrab) if it doesn't work and we can debug together.

**Comment by christopherdowson** [comment]
That’s sorted it - thanks so much!



Now I just need to figure out how to get the variant price next to the size. Learning is fun.

Christopher Dowson

Dowson.
Studio 1897, 109 Vernon House, Friar Lane, Nottingham NG1 6DQ
0115 727 0259 ***@***.***
madebydowson.com
