### ISSUE TITLE
User icon doesn't work

### ISSUE THREAD

**Issue by pythlang** [notrab/headless-dropshipping-starter#46]
I see there was another issue that tried to address this but you closed it #24 .

Yes, when I use the demo online, the icon routes. When I run the project locally, however, it does not function whatsoever. 

When I navigate to  `/#/signin` then it remains on the homepage. When I look at the online demo, there are Links which do not exist in this repository in the same way the other functional Links do. I know in your video you say we must create them, but....

Can you please guide me as to how to 1) fix this and 2) how I would go about using the registration/login functionality in a headless server. What and where would I be pointing this to log-in/register?

Thanks so much

![Screen Shot 2022-01-06 at 21 20 35](https://user-images.githubusercontent.com/23020467/148480913-20e01601-77ff-428a-84fe-4e622ca9e9e0.png)
![Screen Shot 2022-01-06 at 21 21 12](https://user-images.githubusercontent.com/23020467/148480914-4a8d47f8-ccd8-4a3e-b1fc-acd02818faf4.png)

**Comment by notrab** [comment]
Hey

Do you have `NEXT_PUBLIC_SNIPCART_API_KEY` defined? This wouldn't work if you have user logins disabled, or no Printful key.

**Comment by pythlang** [comment]
Thanks for the quick reply; I saw your message but couldn't get to it due to an emergency.

Indeed, I have the `NEXT_PUBLIC_SNIPCART_API_KEY` defined. 

![Screen Shot 2022-01-10 at 07 52 33](https://user-images.githubusercontent.com/23020467/148769333-7290710a-880f-47a0-88d4-b8fd896be94a.png)

Where should I check whether or not user logins are disabled?

**Comment by notrab** [comment]
Can you try this?

> If you don't want to offer the customer dashboard feature to customers: in your merchant dashboard, go to Store configurations → Checkout & cart, and mark the "Allow Guests only" box.

https://docs.snipcart.com/v3/setup/customer-dashboard

**Comment by pythlang** [comment]
Thank you for the link. I will look at this now.

**Comment by pythlang** [comment]
Looks like that solved it. Thanks a bunch, I'm new to the Snipcart platform and working on getting up to speed. 

Please mark as closed.

![image](https://user-images.githubusercontent.com/23020467/148773833-c4247bd5-79ad-4e5f-82a7-96f64ee1658f.png)

![image](https://user-images.githubusercontent.com/23020467/148775204-5221e5ad-7e66-4544-9b84-c06ecc651b69.png)

**Comment by notrab** [comment]
Awesome! I'm glad you got it sorted
