### ISSUE TITLE
Printful API Key changes

### ISSUE THREAD

**Issue by notrab** [notrab/headless-dropshipping-starter#60]
Printful are using newer API keys now, so this is a reminder for anyone looking at past issues related to API access that you may need to create a new API key.

**Comment by ariviom** [comment]
Does this work with the tokens system? New API keys are disabled as of 9/30/22 and I'm getting an error trying to use a token as recommended now by Printful.

`Error: {"code":401,"result":"The access token provided is invalid.","error":{"reason":"Unauthorized","message":"The access token provided is invalid."}}`

**Comment by raqibjs** [comment]
> Does this work with the tokens system? New API keys are disabled as of 9/30/22 and I'm getting an error trying to use a token as recommended now by Printful.
> 
> `Error: {"code":401,"result":"The access token provided is invalid.","error":{"reason":"Unauthorized","message":"The access token provided is invalid."}}`

Hi @ariviom is it working now? Got any solutions?

**Comment by notrab** [comment]
I've updated the `main` branch to use `printful-request@2.0.0` which uses the new token format.
