### ISSUE TITLE
Consider adding a responsive navbar

### ISSUE THREAD

**Issue by Shobhit-Mishra-02** [notrab/headless-dropshipping-starter#69]
I really liked the UI of this ecommerce application, but I think that the navbar should be responsive as the overall design gets spoiled when I decreases the view port width.

**Comment by notrab** [comment]
I’d be happy to merge any PRs on this 🙏

**Comment by Shobhit-Mishra-02** [comment]
Have you checked my PR on this issue ?

**Comment by notrab** [comment]
Hey @Shobhit-Mishra-02 

I've included your commit into another branch I'm working on that brings some improvements to this app!
