### ISSUE TITLE
Why the sign up form is unavailable?

### ISSUE THREAD

**Issue by samdi** [notrab/headless-dropshipping-starter#79]
Hi Jamie,

Thanks for creating this cool store. I'm a low-code developer and I deployed the store but the sign up form is unavailble. How to make it signable? I'm looking forward to hearing some new updates like live search, quick view details (description with variants). Thank you so much

**Comment by notrab** [comment]
Hey

Have you enabled such features inside of Snipcart?

**Comment by samdi** [comment]
Yeah, just explored the Snipcart Checkout & Cart and unchecked "Allow Guests only". It's working now. Thanks a lot!
