### ISSUE TITLE
printful api change to access tokens

### ISSUE THREAD

**Issue by stephangriesel** [notrab/headless-dropshipping-starter#87]
I tried using the private tokens since Printful is not supporting API keys from March 2023. Is this working for this repo yet?

**Comment by notrab** [comment]
Hey @stephangriesel 

I merged support for this in https://github.com/notrab/headless-dropshipping-starter/commit/4604b537d3b35b5ee10321c5cdd4634e3d684072

Does the instructions in the README not work? More info would be great.

Thank you 🙏🏻

**Comment by stephangriesel** [comment]
Ah just saw now I am still behind, thank you!

**Comment by pythlang** [comment]
![image](https://github.com/notrab/headless-dropshipping-starter/assets/23020467/a1ce015f-4c28-450c-81ab-c8a14d23314c)

I needed to provide npm with specificity ```npm install printful-request@2.0.0```

**Comment by notrab** [comment]
@pythlang did you already have the plugin installed? You should be able to do `npm install printful-request@latest` to upgrade the dependency inside an existing project.

**Comment by pythlang** [comment]
> @pythlang did you already have the plugin installed? You should be able to do `npm install printful-request@latest` to upgrade the dependency inside an existing project.

Yes… Fair play, but I didn’t know as it had been a while so I upgraded to the version in the readme

**Comment by notrab** [comment]
@pythlang Is there anything I can do better to improve so others don't have the same issue?
