### ISSUE TITLE
Some error is happening while fetching shipping rates

### ISSUE THREAD

**Issue by adeirjunior** [notrab/headless-dropshipping-starter#96]
I'm not sure why this is happening, but it looks like the error is that the necessary object keys to send through the api had changed

![fetching error](https://user-images.githubusercontent.com/73009242/222871819-d37acf7f-8215-4454-b88e-9648f614084e.png)

**Comment by notrab** [comment]
Have you checked the docs for either? I’d happily accept a PR that fixed this.

**Comment by matt-peck** [comment]
@adeirjunior 

Possible Issues:
1. It looks like you are in Test mode instead of Live
2. I had a similar issue in live mode and found that I had to review the snipcart configuration for shipping. There was a message at the very top that said it needed to verify my business address. 

Hope that helps.

**Comment by adeirjunior** [comment]
@matt-peck 

Thanks for the answer, but it looks like it didn't change anything unless now the development error message is hidden.

![image](https://user-images.githubusercontent.com/73009242/227416196-014ebddd-5bd5-4c54-8823-3d09b6977986.png)

I really was in Test mode previously, but now that I've put in my credit card and obtained the live public API key, it's still the same.

Below are the console log errors.

![2023-03-23](https://user-images.githubusercontent.com/73009242/227416678-6b4768a4-73a4-43e3-b199-99caccc9f9a5.png)

As for configuring my business address, the only things that are empty are ADDRESS 2 and VAT NUMBER. Are these necessary for the WEBHOOK?

**Comment by adeirjunior** [comment]
> Have you checked the docs for either? I’d happily accept a PR that fixed this.

Thank you for the response, but now that I have thought about it more, the problem cannot be happening because of an error in the webhook since your demo is working correctly. So, I must have actually made some incorrect configuration when setting up the webhook on Snipcard.

I believe I followed your Snipcard configuration guide in the readme as instructed. Are there any additional steps required to set it up correctly?
